apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-k8s
  name: hello-k8s
spec:
  containers:
  - image: nicksterling/hello-kubernetes:1
    name: hello-k8s
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

